FROM alpine:3.19.1
RUN apk --no-cache add ca-certificates git

# binaries were created with GoReleaser
# need to copy binaries from folder with correct architecture
# example architecture folder: dist/search_canary_build_linux_arm64/search
# GoReleaser adds _v* to the folder name, but only when GOARCH is amd64 
ARG TARGETARCH
COPY "dist/search_canary_build_linux_${TARGETARCH}*/search" /usr/local/bin/search
COPY contrib/*.tpl contrib/
ENTRYPOINT ["search"]